### ISSUE TITLE
k1ss.org is down.

### ISSUE THREAD

**Issue by aheirman** [kisslinux/kisslinux.github.io#77]
Just a heads up.
It's been down for a couple days.

**Comment by aheirman** [comment]
This might be of interest to you

```
Registered On:
2020-02-14
Expires On:
2022-02-14
Updated On:
2021-02-15```

src https://www.whois.com/whois/k1ss.org

**Comment by mcpcpc** [comment]
please use the mirrors that have been setup: https://kiss.armaanb.net or http://k1ss.net

**Comment by spacedream** [comment]
# https://k1sslinux.org <3

**Comment by spacedream** [comment]
no one knows what happened to real owner of project. i guess jews mafia hijacked again another time another good one. 
ps: just a rumor, cannot confirm. not good feelings anyway.
